// SPDX-FileCopyrightText: 2026 Kavoye
// SPDX-License-Identifier: Apache-2.0

import Foundation

nonisolated enum AIDisclosure {
    static let replyCaption: LocalizedStringResource =
        "AI replies can be wrong. Check important info."

    static let onboardingCaption: LocalizedStringResource =
        "Whichever you choose, you’re talking to AI, not a person. Replies can be wrong, so check anything important."

    static let settingsCaption: LocalizedStringResource =
        "Replies are generated by AI and can contain mistakes. Check important info."

    @MainActor
    static func spokenPrefix() -> String {
        guard !hasSpokenDisclosure else { return "" }
        hasSpokenDisclosure = true
        return String(localized: "You’re talking to AI. ")
    }

    @MainActor
    static func resetSpokenDisclosure() {
        hasSpokenDisclosure = false
    }

    @MainActor
    private static var hasSpokenDisclosure = false
}
